#!/usr/bin/env python3
"""Packs the boot screen's artwork into include/boot_art.h.

    python tools/make_boot_art.py            # needs Pillow

Reads docs/input.png (the hooded MuleSkin at his computer, the same source
docs/twich.py animates), scales it to SIZE x SIZE and quantises it to a
256-colour palette, so the firmware carries one byte a pixel plus a 512-byte
RGB565 palette -- about 26 KB, against roughly 2 MB for the 20-frame GIF.
The ear twitch is not stored at all: ui_boot.cpp redraws it from this one
frame with the same column shifts twich.py uses.

Run it again after changing the source image, and commit the header.
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "..", "docs", "input.png")
OUT  = os.path.join(HERE, "..", "include", "boot_art.h")
SIZE = 160

im = Image.open(SRC).convert("RGB").resize((SIZE, SIZE), Image.LANCZOS)
q = im.quantize(colors=256, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.FLOYDSTEINBERG)
pal = q.getpalette()[:256 * 3]
pal += [0] * (256 * 3 - len(pal))
idx = q.tobytes()

def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

lines = [
    "// Generated by tools/make_boot_art.py from docs/input.png -- do not edit.",
    "// The boot screen's artwork: %dx%d, one palette index a pixel, row-major." % (SIZE, SIZE),
    "#pragma once",
    "#include <stdint.h>",
    "",
    "namespace BootArt {",
    "constexpr int SIZE = %d;" % SIZE,
    "static const uint16_t PALETTE[256] = {",
]
cols = [rgb565(*pal[i * 3:i * 3 + 3]) for i in range(256)]
for i in range(0, 256, 12):
    lines.append("    " + ", ".join("0x%04X" % c for c in cols[i:i + 12]) + ",")
lines.append("};")
lines.append("static const uint8_t PIXELS[%d * %d] = {" % (SIZE, SIZE))
for i in range(0, len(idx), 20):
    lines.append("    " + ", ".join(str(b) for b in idx[i:i + 20]) + ",")
lines.append("};")
lines.append("}  // namespace BootArt")
lines.append("")

with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(lines))
print("%dx%d, %d colours -> %s (%d bytes of pixels)" % (
    SIZE, SIZE, len(set(idx)), os.path.normpath(OUT), len(idx)))
