#!/usr/bin/env python3
"""Packs the MuleSkin artwork into include/muleskin_art.h.

    python tools/make_boot_art.py            # needs Pillow

Reads docs/input.png (the hooded MuleSkin at his computer, the same source
docs/twich.py animates) and writes it SIZE x SIZE as RGB332 bytes -- the
frame buffer's own format, so a row goes to the screen with one pushImage()
and no conversion. It is error-diffused against the RGB332 colours here, on a
PC, rather than left for the panel to round, which is what keeps the dark
gradients from banding. About 100 KB.

One asset, two users: the boot splash draws the whole square, scaled down
into its frame; the MULESKIN background crops it to cover the screen. The ear
twitch is not stored at all -- Theme::drawArtwork() redraws it from this one
frame with the column shifts twich.py uses.

Run it again after changing the source image, and commit the header.
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "..", "docs", "input.png")
OUT  = os.path.join(HERE, "..", "include", "muleskin_art.h")
SIZE = 320

# Palette entry i IS RGB332 byte i, so the quantised indices are the pixels.
pal = []
for i in range(256):
    pal += [((i >> 5) & 7) * 255 // 7, ((i >> 2) & 7) * 255 // 7, (i & 3) * 255 // 3]
pal_img = Image.new("P", (1, 1))
pal_img.putpalette(pal)

im = Image.open(SRC).convert("RGB").resize((SIZE, SIZE), Image.LANCZOS)
q = im.quantize(palette=pal_img, dither=Image.Dither.FLOYDSTEINBERG)
px = q.tobytes()

lines = [
    "// Generated by tools/make_boot_art.py from docs/input.png -- do not edit.",
    "// The MuleSkin artwork: %dx%d, one RGB332 byte a pixel, row-major." % (SIZE, SIZE),
    "#pragma once",
    "#include <stdint.h>",
    "",
    "namespace MuleSkinArt {",
    "constexpr int SIZE = %d;" % SIZE,
    "static const uint8_t PIXELS[%d * %d] = {" % (SIZE, SIZE),
]
for i in range(0, len(px), 24):
    lines.append("    " + ",".join(str(b) for b in px[i:i + 24]) + ",")
lines.append("};")
lines.append("}  // namespace MuleSkinArt")
lines.append("")

with open(OUT, "w", newline="\n") as f:
    f.write("\n".join(lines))
print("%dx%d RGB332, %d distinct -> %s (%d bytes)" % (
    SIZE, SIZE, len(set(px)), os.path.normpath(OUT), len(px)))
